name: dl-nlp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.0
  - blas=1.0
  - boto3=1.13.0
  - botocore=1.16.0
  - brotlipy=0.7.0
  - ca-certificates=2020.1.1
  - catalogue=1.0.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - cymem=2.0.3
  - cython-blis=0.4.1
  - docutils=0.15.2
  - freetype=2.9.1
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2019.4
  - jmespath=0.9.5
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - libcxx=10.0.0
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - llvm-openmp=4.0.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - murmurhash=1.0.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.0.0
  - pip=20.0.2
  - plac=0.9.6
  - preshed=3.0.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.5.0
  - readline=7.0
  - regex=2020.4.4
  - requests=2.23.0
  - s3transfer=0.3.3
  - sacremoses=0.0.41
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=46.1.3
  - six=1.14.0
  - spacy=2.2.3
  - spacy-model-en_core_web_sm=2.2.5
  - sqlite=3.31.1
  - srsly=1.0.0
  - thinc=7.3.0
  - tk=8.6.8
  - torchvision=0.6.0
  - tqdm=4.45.0
  - urllib3=1.25.9
  - wasabi=0.6.0
  - wheel=0.34.2
  - xz=5.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - filelock=
    - numpy=
    - packaging=
    - pyparsing=
    - sentencepiece=
    - tokenizers=
    - transformers=

